name: Android CI

on:
  push:
    paths:
      - "**.gradle"
      - "**.rs"
      - "**/Cargo.toml"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "**.gradle"
      - "**.rs"
      - "**/Cargo.toml"
      - ".github/workflows/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          targets: 'armv7-linux-androideabi i686-linux-android aarch64-linux-android x86_64-linux-android'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :module:zipRelease